#!/usr/bin/env python3
"""Generate ui-new/EmojiGlyphs.h: small 11x11 monochrome emoji glyphs + a
shortcode lookup table, for inline rendering in chat bubbles. Sent over-air as
the ASCII shortcode (e.g. ':)') so other clients stay interoperable."""
import math, os

S = 11

class Bmp:
    def __init__(self, n=S):
        self.n = n; self.px = [[0]*n for _ in range(n)]
    def set(self, x, y):
        if 0 <= x < self.n and 0 <= y < self.n: self.px[y][x] = 1
    def disc(self, cx, cy, r):
        for y in range(-r, r+1):
            for x in range(-r, r+1):
                if x*x + y*y <= r*r: self.set(cx+x, cy+y)
    def ring(self, cx, cy, r):
        for a in range(0, 360, 12):
            self.set(round(cx + r*math.cos(math.radians(a))),
                     round(cy + r*math.sin(math.radians(a))))
    def arc(self, cx, cy, r, a0, a1):
        a = a0
        while a <= a1:
            self.set(round(cx + r*math.cos(math.radians(a))),
                     round(cy + r*math.sin(math.radians(a)))); a += 8
    def hline(self, x0, x1, y):
        for x in range(min(x0,x1), max(x0,x1)+1): self.set(x, y)
    def vline(self, x, y0, y1):
        for y in range(min(y0,y1), max(y0,y1)+1): self.set(x, y)

def face(b): b.ring(5, 5, 5)
def eyes(b): b.set(3,4); b.set(7,4)

def smile(b): face(b); eyes(b); b.arc(5,4,3,30,150)
def sad(b):   face(b); eyes(b); b.arc(5,9,3,210,330)
def laugh(b): face(b); eyes(b);
def wink(b):  face(b); b.hline(2,4,4); b.set(7,4); b.arc(5,4,3,30,150)
def surprise(b): face(b); eyes(b); b.disc(5,7,1)
def cool(b):  face(b); b.hline(2,8,4); b.arc(5,4,3,30,150)
def meh(b):   face(b); eyes(b); b.hline(3,7,8)
def neutral(b): face(b); eyes(b); b.hline(3,7,7)
def cry(b):   face(b); eyes(b); b.arc(5,9,3,210,330); b.vline(3,5,8)
def heart(b):
    b.disc(3,4,2); b.disc(7,4,2)
    for y in range(4,10):
        w = 9 - (y-3)
        b.hline(5-w//2, 5+w//2, y)

# laugh needs an open mouth (filled)
def laugh2(b):
    face(b); eyes(b)
    for y in range(7,9):
        b.hline(3,7,y)
    b.hline(4,6,9)

GLYPHS = [
    ("smile", smile), ("sad", sad), ("laugh", laugh2), ("wink", wink),
    ("surprise", surprise), ("cool", cool), ("meh", meh), ("neutral", neutral),
    ("cry", cry), ("heart", heart),
]

# shortcodes -> glyph name (ORDER MATTERS: longest / most-specific first)
CODES = [
    (":'(", "cry"), (":+1:", "heart"),  # (+1 maps to heart for now)
    (":D", "laugh"), (";)", "wink"), ("B)", "cool"), ("<3", "heart"),
    (":o", "surprise"), (":O", "surprise"), (":/", "meh"), (":|", "neutral"),
    (":)", "smile"), (":(", "sad"),
]

def to_xbm(b):
    bpr = (b.n + 7)//8; out = []
    for y in range(b.n):
        for by in range(bpr):
            v = 0
            for bit in range(8):
                x = by*8 + bit
                if x < b.n and b.px[y][x]: v |= (1 << bit)
            out.append(v)
    return out

def main():
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "..", "examples", "companion_radio", "ui-new", "EmojiGlyphs.h")
    L = ["#pragma once", "",
         "// Auto-generated by sim/gen_emoji.py -- do not edit by hand.",
         "// 11x11 monochrome emoji glyphs + ASCII-shortcode lookup for inline chat rendering.",
         "#include <stdint.h>", "", "namespace emoji {", "",
         f"constexpr int EMOJI_W = {S};", f"constexpr int EMOJI_H = {S};", ""]
    bpr = (S+7)//8
    for name, fn in GLYPHS:
        b = Bmp(); fn(b); data = to_xbm(b)
        rows = [", ".join(f"0x{v:02x}" for v in data[i:i+bpr]) for i in range(0, len(data), bpr)]
        L.append(f"static const uint8_t g_{name}[] = {{")
        L.append("  " + ",\n  ".join(rows))
        L.append("};"); L.append("")
    L.append("struct Shortcode { const char* code; const uint8_t* bits; };")
    L.append("static const Shortcode SHORTCODES[] = {")
    for code, gname in CODES:
        esc = code.replace("\\", "\\\\").replace('"', '\\"')
        L.append(f'  {{ "{esc}", g_{gname} }},')
    L.append("};")
    L.append("static const int SHORTCODE_COUNT = sizeof(SHORTCODES) / sizeof(SHORTCODES[0]);")
    L.append("")
    L.append("// If `p` starts with a known shortcode, return its glyph bits + set *len; else NULL.")
    L.append("inline const uint8_t* match(const char* p, int* len) {")
    L.append("  for (int i = 0; i < SHORTCODE_COUNT; i++) {")
    L.append("    const char* c = SHORTCODES[i].code; int n = 0;")
    L.append("    while (c[n] && p[n] == c[n]) n++;")
    L.append("    if (c[n] == 0) { *len = n; return SHORTCODES[i].bits; }")
    L.append("  }")
    L.append("  return nullptr;")
    L.append("}")
    L.append("")
    L.append("}  // namespace emoji")
    L.append("")
    open(out, "w").write("\n".join(L))
    print("wrote", os.path.normpath(out))

if __name__ == "__main__":
    main()
